---
title: Laureano.
timezone: UTC
lang: pt
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contato@laureano.eu
description: Videomaker por profissão. Roteirista por masoquismo.
baseurl: ''
url: ''
twitter_username: laureanoeu
github_username: 
theme: hitchens-theme
show_excerpts: true
hide_credits: true
hide_search: true
feed_icon: /favicon.ico
font-awesome:
  assets: true
disqus:
    shortname: laureano
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-archives
- jekyll-sitemap
- jekyll-gist
- jekyll-seo-tag
- jemoji
- jekyll-font-awesome-sass
- kramdown-parser-gfm
paginate: 10
paginate_path: "/page/:num/"
jekyll-archives:
  enabled: all
  layout: archive
  slug_mode: latin
  permalinks:
    category: '/category/:name/'