---
title: Laureano.
timezone: UTC
lang: pt-BR
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contato@laureano.eu
description: Videomaker por profissão.

Roteirista por masoquismo.
baseurl: ''
url: ''
twitter_username: laureano_eu
github_username: 
theme: hitchens-theme
show_excerpts: true
hide_credits: true
font-awesome:
  assets: true
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: laureano
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-archives
- jekyll-font-awesome-sass
paginate: 10
paginate_path: "/page/:num/"
jekyll-archives:
  enabled: all
  layout: archive
  slug_mode: latin
  permalinks:
    category: '/category/:name/'