---
title: Laureano.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  pages:
    title: Pages
    output: true
email: autor@laureano.eu
description: Videomaker por profissão. <br> Roteirista por masoquismo.
baseurl: ''
url: ''
twitter_username: law_reano
github_username: law_reano
theme: hitchens-theme
show_excerpts: true
plugins:
- jekyll-feed
- jekyll-paginate
paginate: 20
paginate_path: "/page/:num/"
