---
title: Laureano.
timezone: UTC
lang: pt-br
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: autor@laureano.eu
description: Videomaker por profissão.<p>Roteirista por masoquismo.
baseurl: ''
url: ''
twitter_username: law_reano
github_username: law_reano
theme: hitchens-theme
show_excerpts: true
hide_credits: true
font-awesome:
  assets: true
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-archives
- jekyll-font-awesome-sass
paginate: 20
paginate_path: "/page/:num/"
jekyll-archives:
  enabled: all
  layout: archive
  slug_mode: latin
  permalinks:
    category: '/category/:name/'
