---
title: Laureano.
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
future: false
email: laureatorio@gmail.com
description: Videomaker por profissão. Roteirista por masoquismo.
baseurl: ''
url: ''
instagram_username: laureator.io
github_username: tropicaos
theme: hitchens-theme
show_excerpts: true
hide_credits: true
hide_search: true
feed_icon: /favicon.ico
font-awesome:
  assets: true
google_analytics: G-00YCQBLT2C
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-archives
- jekyll-sitemap
- jekyll-gist
- jekyll-seo-tag
- jemoji
- jekyll-font-awesome-sass
- kramdown-parser-gfm
paginate: 10
paginate_path: "/page/:num/"
jekyll-archives:
  enabled: all
  layout: archive
  slug_mode: latin
  permalinks:
    category: '/category/:name/'