---
title: Laureano.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: autor@laureano.eu
description: Videomaker por profissão. <br> Roteirista por masoquismo.
baseurl: ''
url: ''
twitter_username: law_reano
github_username: law_reano
theme: hitchens-theme
show_excerpts: true
hide_credits: true
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-archives
paginate: 20
paginate_path: "/page/:num/"
jekyll-archives:
  enabled: all
  layout:
    category: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
